device: cuda
dataset:
  name: CIFAR10
model:
  type: cifar
  name: wrn
  init_mode: kaiming_fan_in
  wrn:
    depth: 28
    initial_channels: 16
    widening_factor: 10
    drop_rate: 0.0
train:
  use_apex: true
  seed: 3
  precision: O0
  batch_size: 128
  subdivision: 1
  optimizer: sgd
  base_lr: 0.1
  momentum: 0.9
  nesterov: true
  weight_decay: 5e-4
  output_dir: experiments/CIFAR10/BASELINE_WRN//3
  log_period: 100
  checkpoint_period: 100
  val_ratio: 0.1
  use_test_as_val: false
  use_tensorboard: true
  distributed: false
  dataloader:
    num_workers: 6
    drop_last: true
    pin_memory: true
validation:
  batch_size: 256
  dataloader:
    num_workers: 2
    drop_last: false
    pin_memory: true
scheduler:
  epochs: 200
  type: multistep
  milestones:
  - 60
  - 120
  - 160
  lr_decay: 0.2
augmentation:
  use_random_crop: true
  use_random_horizontal_flip: true
  use_cutout: false
  use_random_erasing: false
  use_dual_cutout: false
  use_mixup: false
  use_ricap: false
  use_cutmix: false
  use_label_smoothing: false
  random_crop:
    padding: 4
    fill: 0
    padding_mode: constant
  random_horizontal_flip:
    prob: 0.5
tensorboard:
  train_images: false
  val_images: false
  model_params: false
